name: 🐛 Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      placeholder: Drag and drop screenshots here...

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v1.0.0 or commit hash
