name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "Video Tools"
        - "Image Tools"
        - "PDF Tools"
        - "Regex Tester"
        - "Unit Converter"
        - "Backend API"
        - "Frontend UI"
        - "Desktop App (Tauri)"
        - "Web App (Docker)"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - "Linux"
        - "Windows"
        - "macOS"
        - "Web (Docker)"
        - "All"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: TaskPlex version (e.g., v1.0.0, commit hash, or "latest")
      placeholder: v1.0.0 or commit hash
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11]
        - Python: [e.g., 3.11.5]
        - Node.js: [e.g., 20.10.0]
        - Browser: [e.g., Chrome 120] (if web)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Relevant logs or error messages
      placeholder: Paste logs or error messages here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug has not been reported
          required: true
        - label: I have provided all relevant information above
          required: true

