name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I also considered..."
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - "Video Tools"
        - "Image Tools"
        - "PDF Tools"
        - "Regex Tester"
        - "Unit Converter"
        - "Backend API"
        - "Frontend UI"
        - "Desktop App (Tauri)"
        - "Web App (Docker)"
        - "Infrastructure/DevOps"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be useful"
        - "High - Important for my use case"
        - "Critical - Blocking my workflow"
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: "As a [type of user], I want to [goal] so that [benefit]..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images or describe the UI/UX...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or examples
      placeholder: Add any other context about the feature request here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature has not been requested
          required: true
        - label: I have provided all relevant information above
          required: true

