name: ❓ Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      placeholder: Any relevant details...
